# Frontend Dockerfile

# Use an official nginx image to serve static content
FROM nginx:alpine

# Copy frontend files (HTML/JS) to the nginx html folder
COPY . /usr/share/nginx/html

# Expose port 80 for the frontend
EXPOSE 80
