replicaCount: 1

backend:
  image:
    repository: backend
    tag: latest
  service:
    port: 3000

frontend:
  image:
    repository: frontend
    tag: latest
  service:
    port: 80

persistence:
  size: 1Gi
