replicaCount: 1

namespace:
  name: dev-namespace

backend:
  image:
    repository: backend
    tag: latest
  service:
    type: ClusterIP 
    port: 3000

frontend:
  deployment:
    replicas: 2
  image:
    repository: frontend
    tag: latest
  service:
    type: ClusterIP
    port: 80

persistence:
  size: 1Gi
